version: "3.9"

services:
  app:
    build: .
    container_name: xenia-web-service
    restart: unless-stopped

    ports:
      - "36001:36000"

    environment:
      API_PORT: 36000
      MONGO_URI: mongodb://mongo:27017/xenia
      SWAGGER_API: "true"
      nginx: "true"

    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: xenia-mongo
    restart: unless-stopped
    ports:
      - '27018:27017'

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
#vibe coded to hell lol#
